### PR TITLE
add google analytics, add blank search placeholder, more

### LINKED ISSUE #176: figure out how to handle empty search
When nothing is typed into a search box, some results still display below it. This is so people can jump right in more easily, with less steps.

But it also confuses people. What are those results, are they arbitrary, did I accidentally type something into the search, are they all of the genes, are they special.

Should we pre-populate each search box with something, eg "dna" for genes. Should we only show the top 5 results when nothing's typed in to make it clear it's not all of the genes in the database. Should we put a note between the search box and the result table that says "try these" to indicate it's a blank search.

### PR DESCRIPTION
**Pull request by vincerubinetti**
- add google analytics tracking script
- include Paeruginosa-da folder from old adage
- simplify redirect scripts now that site is guaranteed to be hosted at root level (and not eg. github.io/adage-frontend)
- fix bug with search box being expanded by default from local storage
- add placeholder text above gene and experiment search
- update workerize-loader
- add sample # col to experiment activities table on signatures page
- change p value epsilon to arbitrary 1x10^-8 (1e-8)
- remove unnecessary rounding of mantissa in toExponential

gbdqhMlcil

### CODE REVIEW

**Review by dongbohu — APPROVED** [review]

**Review by cgreene — APPROVED** [review]
Looks good! 👍

**Comment by vincerubinetti** [comment]
Still fiddling around with some redirecting stuff. Will merge soon.

**Comment by dongbohu** [comment]
@vincerubinetti : If we put the whole `Paeruginosa-da` directory in `public` and rebuild the frontend, does `adage.greenelab.com/Paeruginosa-da` work w/o redirect? If it works, then we don't have to keep the old-adage running. I am attaching `Paeruginosa-da` as a tarball file here.
[Paeruginosa-da.tar.gz](https://github.com/greenelab/adage-frontend/files/4657932/Paeruginosa-da.tar.gz)

**Comment by vincerubinetti** [comment]
I had considered that. I believe whatever's in the public folder gets copied to `/build`, yes. We can move that folder there. Though I do want to keep the old adage running for a while to serve as a comparison for results. Especially regarding #111

**Comment by dongbohu** [comment]
@vincerubinetti: I will definitely keep old-adage running for now. It will be shut down only when we feel ready.

**Pull request merged**
