### PR TITLE
Enriched signatures

### PR DESCRIPTION
**Pull request by vincerubinetti**
- adds basic/initial enriched signatures section
  - get gene count and models associated with model
  - implements hypergeometric and false discovery rate calculations
  - port over other math functions from old frontend
- add default response limit
- refactors and simplifies fetch actions a bit. removes some functionality, to be replaced later by the CAF library
  - changes response caching from sessionStorage to just keeping it in memory (equivalent)
  - removes generator-runner pattern from fetch actions
  - removes fetch AbortController from fetch actions

image

### CODE REVIEW

**Comment by dongbohu** [comment]
Two quick comments:
* You need to update the version to pass circleci test;
* Did you compare the P-values with the ones in original adage web UI?

**Comment by vincerubinetti** [comment]
> Two quick comments:
> 
> * You need to update the version to pass circleci test;
> * Did you compare the P-values with the ones in original adage web UI?

Will increment the version.

Yes I compared some. Perhaps you could do some spot checks as well to increase our confidence.

In the near future (next couple of weeks) I intend to start including tests in this project for everything, including the p-values.

**Comment by dongbohu** [comment]
A URL like this:
https://deploy-preview-57--adage-frontend.netlify.com/genes?selected=2-1
should include `mlmodel` parameter too, because the calculation is based on signatures, which depend on which machine learning model has been selected.

**Comment by vincerubinetti** [comment]
> A URL like this:
> https://deploy-preview-57--adage-frontend.netlify.com/genes?selected=2-1
> should include `mlmodel` parameter too, because the calculation is based on signatures, which depend on which machine learning model has been selected.

Okay, I can integrate that into the next PR. That's sort of a separate issue: url persistence of the selected model. FWIW the calculation does indeed take into account the selected model.

**Comment by dongbohu** [comment]
Yes, I noticed that. If mlmodel were not considered into the calculation, the results would have been very different.

**Review by dongbohu — APPROVED** [review]
Code looks good!

**Comment by vincerubinetti** [comment]
By the way, a while ago we had talked about renaming `mlmodel` to just `model`. Can we do that before merging this PR?

Also, in the `participations` query, is `related-genes` the best parameter name for that? The old code base doesn't use that terminology anywhere. I think it should be just `selected-genes` or even just `genes`.

**Pull request merged**
