### PR TITLE
add tribe pickled gene set table

### PR DESCRIPTION
**Pull request by vincerubinetti**
image

p-values for some reason don't match the [old adage](https://adage.greenelab.com/#/signature/1), even when I'm using the [same code verbatim](https://github.com/greenelab/adage-server/blob/985f36df55b0aea5378e090cda85170148f6a7f7/interface/src/app/signature/signature.js).

- add enriched gene set table section
- add calculation for enriched gene sets
- add exponential display for p values
- remove object flattening for normalizing
- fix table sorting for string numbers
- change table InView to trigger once
- make table rows able to expand vertically
- add selected organism to state

### CODE REVIEW

**Comment by dongbohu** [comment]
I compared that API output between:
https://adage.greenelab.com/tribe_client/return_unpickled_genesets?organism=Pseudomonas+aeruginosa
and:
https://py3-adage.greenelab.com/api/v1/tribe_client/return_unpickled_genesets?organism=Pseudomonas+aeruginosa
the results are equivalent (except that the order of key/value pairs are different). I noticed that in the screnshot that you attached, only the first two rows' p-values are different. Could it be due to some different ways of rounding errors between the two approaches?

**Comment by vincerubinetti** [comment]
Okay I found the issue. I believe it's upstream in `stdlib`'s `cdf` function being inaccurate at many decimal places.

Here's an example:
```
k = 1
K = 71
n = 86
N = 2443

0.9243998310893528 // result from new adage
0.924399831089443 // result from old adage
0.92439983108944501211 // result from R
```

I ran R online from this site: https://rdrr.io/snippets/

As you can see, the results are almost identical, except after like decimal place 12. Which is probably why all of the p-values match between the old and the new adage, except for the really really small ones.

**Comment by dongbohu** [comment]
The values on the new adage make more sense to me. The negative p-values on the old adage server bothered me.

**Comment by cgreene** [comment]
Yea - the p-values being negative is obviously wrong. I realize it's numerical precision, but I prefer this version.

**Review by dongbohu — APPROVED** [review]

**Review by dongbohu — APPROVED** [review]

**Comment by vincerubinetti** [comment]
- add enriched gene set table section
- add calculation for enriched gene sets
- add exponential display for p values
- remove object flattening for normalizing
- fix table sorting for string numbers
- change table InView to trigger once
- make table rows able to expand vertically
- add selected organism to state

**Pull request merged**
