### PR TITLE
convert to github actions

### PR DESCRIPTION
**Pull request by vincerubinetti**
I think ultimately GitHub actions are the way of the future, so I want to try to move over now. I also find them to be simpler and easier to deal with than Circle CI (so far).

This PR does not implement the custom GitHub action I had mentioned before, but does replace the python script with a javascript script to check the version number. That way, I can maintain it more easily (since I don't know Python), and it can possibly be converted to a GitHub action in the future.

### CODE REVIEW

**Comment by dongbohu** [comment]
What's the advantage of using this feature? You still need to hard code the repo's name in the script. The only difference is that it is written in JS instead of Python now.

**Comment by vincerubinetti** [comment]
As I said, I can maintain it myself instead of relying on your help. Also I might be able to make a reusable GitHub action out of it in the future.

**Comment by vincerubinetti** [comment]
I also added some checks for things like blank version numbers, and invalid version numbers (eg `3.a.2`).

**Comment by dongbohu** [comment]
CircleCI fails now. Do you still need it for deployment?

**Comment by vincerubinetti** [comment]
No, we'll delete it after we confirm that this is working properly.

**Comment by dongbohu** [comment]
Does your script include deployment to the AWS server? I didn't see it.

**Comment by vincerubinetti** [comment]
Per @dhimmel we probably just have to merge this and see if it works. Will revert immediately if something goes wrong. Haven't disabled Circle CI yet.

**Pull request merged**
