### PR TITLE
Fix gene network graph discrepancy with old adage

### PR DESCRIPTION
**Pull request by vincerubinetti**
- modify gene graph construction and filtering code
- write tests for gene graph construction and filtering code
- dont clear search box when pressing enter to select
- updates test dummy data to reflect small gene changes to database

### CODE REVIEW

**Comment by vincerubinetti** [comment]
The calculate enriched signatures test failed. The pValues changed slightly for some reason. 

I did update the `/dummy-data` master genes list because I remember @dongbohu added some new `standardName`'s, but I don't know why that would've affected the pvalues.

Any ideas @dongbohu? Did any of the gene ids change? Did the gene participation values change?

**Comment by vincerubinetti** [comment]
well i just updated the test to pass with the new values. you can still look here to see the differences:
https://github.com/greenelab/adage-frontend/runs/766844937

**Comment by dongbohu** [comment]
The new adage server includes more genes, but the original genes have same IDs. Is the p-value depend solely on the dummy data?

**Comment by vincerubinetti** [comment]
> The participation data of PA4638 is now included. On the old adage server, this gene didn’t exist in the database.

Your comment on slack. This probably explains the slight difference. One extra participating gene would be enough to slightly change the p value the way we're seeing. So I'm thinking it's okay.

**Comment by dongbohu** [comment]
To clarify, this gene's participation data was added a few weeks ago (before we migrated `adage.greenelab.com`).

**Review by dongbohu — APPROVED** [review]

**Comment by vincerubinetti** [comment]
> To clarify, this gene's participation data was added a few weeks ago (before we migrated `adage.greenelab.com`).

Looks like the last PR for the frontend was merged ~22 days ago, so I guess that backend change was done slightly after that, which explains why none of my tests failed.

**Pull request merged**
