### PR TITLE
Setup redux

### PR DESCRIPTION
**Pull request by vincerubinetti**
- sets up redux, immer, redux-logger, redux-actions, redux-thunk, redux-thunk-actions, redux-sequence-action, and redux selectors
- installs redux-batched-actions for later use
- sets up basic file structure for backend queries
- actually retrieves model list from backend
- includes error message when model query fails
- makes model select actually select a model, and indicates which model is selected
- rearranges header layout on mobile screens and modifies model select popup

### CODE REVIEW

**Review by dongbohu — COMMENTED** [review]
Code looks good. Note that I just filed a PR that affects you: all supported URLs have been tweaked a little bit, so the URL has been changed from:
```.../api/v1/models/...```
to:
```.../api/v1/model/...```
It was modified so that the API URLs will be consistent with the ones used in Python 2.X servers.

**Comment by vincerubinetti** [comment]
Just noticed that when everything broke, haha. I'll update it.

**Review by dongbohu — APPROVED** [review]
I am approving it now.

**Comment by vincerubinetti** [comment]
Also adding an error message for when the model query fails:
image

**Pull request merged**
