### PR TITLE
start adding gene results

### PR DESCRIPTION
**Pull request by vincerubinetti**
- adds single gene search results and selecting/deselecting
- adds gene details/info page
- add dedicated actions for getting model/gene/etc details/info
- opens details/info pages in new tabs
- change the way reducers and selectors work a bit

### CODE REVIEW

**Comment by dongbohu** [comment]
Code looks good. On this screen:
adage-front
do we need the column names (`scientific name`, `systematic name`, etc)?

**Comment by vincerubinetti** [comment]
@dongbohu Maybe eventually. Ideally, it would be obvious enough that we wouldn't need any headers, but since these field names aren't very intuitive, maybe we should.

I was thinking about adding sorting in the future. I'll add headers then. This is sort of a piecemeal PR anyway, since multi-search doesn't work yet.

**Comment by vincerubinetti** [comment]
A side note, I've added an artificial 1 second delay to all queries to help me with testing and debugging. It's so useful to me that I want to keep it in there (rather than remove it and readd it for every new PR) until the frontend reaches a more fully formed state. Maybe when we're out of "alpha" territory and into "beta".

**Comment by dongbohu** [comment]
Yes, I saw the code for 1-sec delay. It is perfectly fine to keep it for now. You may also want to ask the local adage users (such as @ajlee21) to evaluate the web UI. They may have good thoughts or expectations on what it should look like. 

I am approving this PR.

**Review by dongbohu — APPROVED** [review]

**Comment by vincerubinetti** [comment]
@dongbohu I agree. I will ask them their opinion. But since their bandwidth is more limited (they have many other things going on), I was going to ask them at larger milestones. Like say, maybe when the multi-gene search is done.

**Pull request merged**
